backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "episode"
    label: "Episodes"
    folder: "content/episode"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Episode Number", name: "episode", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Audio File URL", name: "podcast", widget: "string"}
      - {label: "Duration", name: "podcast_duration", widget: "string"}
      - {label: "Explicit", name: "explicit", widget: "select", options: ["yes", "no"], default: "no"}
      - {label: "Body", name: "body", widget: "markdown"}